[package]
name = "db-explorer-rs"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
serde = "1.0.130"
serde_json = "1.0.70"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json", "msgpack", "uuid"]